In [1]:
import tensorflow as tf

2021-12-26 15:19:34.210464: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0


In [4]:
v = tf.constant([[1,2,3,4],[5,6,7,8]])

2021-12-26 15:20:07.969230: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-26 15:20:07.969872: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-12-26 15:20:08.015484: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-26 15:20:08.016067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1070 computeCapability: 6.1
coreClock: 1.695GHz coreCount: 16 deviceMemorySize: 7.92GiB deviceMemoryBandwidth: 238.66GiB/s
2021-12-26 15:20:08.016090: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-12-26 15:20:08.019142: I tensorflow/stream_executor/platform/de

In [7]:
d = tf.constant([[1,0]])

In [8]:
tf.matmul(d, v)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [14]:
sp = tf.sparse.from_dense(d)
print('sp', sp)
i = tf.SparseTensor(indices=sp.indices, values=sp.indices[:, 1], dense_shape=sp.dense_shape)
w = tf.SparseTensor(indices=sp.indices, values=sp.values, dense_shape=sp.dense_shape)
print('i', i)
print('w', w)

sp SparseTensor(indices=tf.Tensor([[0 0]], shape=(1, 2), dtype=int64), values=tf.Tensor([1], shape=(1,), dtype=int32), dense_shape=tf.Tensor([1 2], shape=(2,), dtype=int64))
i SparseTensor(indices=tf.Tensor([[0 0]], shape=(1, 2), dtype=int64), values=tf.Tensor([0], shape=(1,), dtype=int64), dense_shape=tf.Tensor([1 2], shape=(2,), dtype=int64))
w SparseTensor(indices=tf.Tensor([[0 0]], shape=(1, 2), dtype=int64), values=tf.Tensor([1], shape=(1,), dtype=int32), dense_shape=tf.Tensor([1 2], shape=(2,), dtype=int64))


In [16]:
tf.nn.embedding_lookup_sparse(v, i, w, combiner='sum')

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>